<?php
return [
    'service_manager' => [
        'factories' => [
            \trello\V1\Rest\Board\BoardResource::class => \trello\V1\Rest\Board\BoardResourceFactory::class,
            \trello\V1\Rest\Column\ColumnResource::class => \trello\V1\Rest\Column\ColumnResourceFactory::class,
            \trello\V1\Rest\Task\TaskResource::class => \trello\V1\Rest\Task\TaskResourceFactory::class,
            \trello\V2\Rest\Board\BoardResource::class => \trello\V2\Rest\Board\BoardResourceFactory::class,
            \trello\V2\Rest\Column\ColumnResource::class => \trello\V2\Rest\Column\ColumnResourceFactory::class,
            \trello\V2\Rest\Task\TaskResource::class => \trello\V2\Rest\Task\TaskResourceFactory::class,
            \trello\V3\Rest\Board\BoardResource::class => \trello\V3\Rest\Board\BoardResourceFactory::class,
            \trello\V3\Rest\Column\ColumnResource::class => \trello\V3\Rest\Column\ColumnResourceFactory::class,
            \trello\V3\Rest\Task\TaskResource::class => \trello\V3\Rest\Task\TaskResourceFactory::class,
        ],
    ],
    'router' => [
        'routes' => [
            'trello.rest.board' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/board[/:board_id]',
                    'defaults' => [
                        'controller' => 'trello\\V1\\Rest\\Board\\Controller',
                    ],
                ],
            ],
            'trello.rest.column' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/column[/:column_id]',
                    'defaults' => [
                        'controller' => 'trello\\V1\\Rest\\Column\\Controller',
                    ],
                ],
            ],
            'trello.rest.task' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/task[/:task_id]',
                    'defaults' => [
                        'controller' => 'trello\\V1\\Rest\\Task\\Controller',
                    ],
                ],
            ],
            'trello.rest.test' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/test[/:test_id]',
                    'defaults' => [
                        'controller' => 'trello\\V2\\Rest\\Test\\Controller',
                    ],
                ],
            ],
            'trello.rest.jhb' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/jhb[/:jhb_id]',
                    'defaults' => [
                        'controller' => 'trello\\V3\\Rest\\Jhb\\Controller',
                    ],
                ],
            ],
        ],
    ],
    'api-tools-versioning' => [
        'uri' => [
            0 => 'trello.rest.board',
            1 => 'trello.rest.column',
            2 => 'trello.rest.task',
            3 => 'trello.rest.test',
            4 => 'trello.rest.jhb',
        ],
        'default_version' => 3,
    ],
    'api-tools-rest' => [
        'trello\\V1\\Rest\\Board\\Controller' => [
            'listener' => \trello\V1\Rest\Board\BoardResource::class,
            'route_name' => 'trello.rest.board',
            'route_identifier_name' => 'board_id',
            'collection_name' => 'board',
            'entity_http_methods' => [
                0 => 'GET',
            ],
            'collection_http_methods' => [
                0 => 'GET',
            ],
            'collection_query_whitelist' => [],
            'page_size' => '25',
            'page_size_param' => '',
            'entity_class' => \trello\V1\Rest\Board\BoardEntity::class,
            'collection_class' => \trello\V1\Rest\Board\BoardCollection::class,
            'service_name' => 'board',
        ],
        'trello\\V1\\Rest\\Column\\Controller' => [
            'listener' => \trello\V1\Rest\Column\ColumnResource::class,
            'route_name' => 'trello.rest.column',
            'route_identifier_name' => 'column_id',
            'collection_name' => 'column',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'DELETE',
                2 => 'PUT',
                3 => 'PATCH',
                4 => 'GET',
                5 => 'DELETE',
                6 => 'PUT',
                7 => 'PATCH',
            ],
            'collection_http_methods' => [
                0 => 'POST',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'POST',
                4 => 'PATCH',
                5 => 'PUT',
            ],
            'collection_query_whitelist' => [],
            'page_size' => '25',
            'page_size_param' => '',
            'entity_class' => \trello\V1\Rest\Column\ColumnEntity::class,
            'collection_class' => \trello\V1\Rest\Column\ColumnCollection::class,
            'service_name' => 'column',
        ],
        'trello\\V1\\Rest\\Task\\Controller' => [
            'listener' => \trello\V1\Rest\Task\TaskResource::class,
            'route_name' => 'trello.rest.task',
            'route_identifier_name' => 'task_id',
            'collection_name' => 'task',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'POST',
                5 => 'GET',
                6 => 'PATCH',
                7 => 'PUT',
                8 => 'DELETE',
                9 => 'POST',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
                2 => 'PATCH',
                3 => 'PUT',
                4 => 'DELETE',
                5 => 'GET',
                6 => 'POST',
                7 => 'PATCH',
                8 => 'PUT',
                9 => 'DELETE',
            ],
            'collection_query_whitelist' => [],
            'page_size' => '25',
            'page_size_param' => '',
            'entity_class' => \trello\V1\Rest\Task\TaskEntity::class,
            'collection_class' => \trello\V1\Rest\Task\TaskCollection::class,
            'service_name' => 'task',
        ],
        'trello\\V2\\Rest\\Board\\Controller' => [
            'listener' => \trello\V2\Rest\Board\BoardResource::class,
            'route_name' => 'trello.rest.board',
            'route_identifier_name' => 'board_id',
            'collection_name' => 'board',
            'entity_http_methods' => [
                0 => 'GET',
            ],
            'collection_http_methods' => [
                0 => 'GET',
            ],
            'collection_query_whitelist' => [],
            'page_size' => '25',
            'page_size_param' => '',
            'entity_class' => \trello\V2\Rest\Board\BoardEntity::class,
            'collection_class' => \trello\V2\Rest\Board\BoardCollection::class,
            'service_name' => 'board',
        ],
        'trello\\V2\\Rest\\Column\\Controller' => [
            'listener' => \trello\V2\Rest\Column\ColumnResource::class,
            'route_name' => 'trello.rest.column',
            'route_identifier_name' => 'column_id',
            'collection_name' => 'column',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'DELETE',
                2 => 'PUT',
                3 => 'PATCH',
            ],
            'collection_http_methods' => [
                0 => 'POST',
                1 => 'PATCH',
                2 => 'PUT',
            ],
            'collection_query_whitelist' => [],
            'page_size' => '25',
            'page_size_param' => '',
            'entity_class' => \trello\V2\Rest\Column\ColumnEntity::class,
            'collection_class' => \trello\V2\Rest\Column\ColumnCollection::class,
            'service_name' => 'column',
        ],
        'trello\\V2\\Rest\\Task\\Controller' => [
            'listener' => \trello\V2\Rest\Task\TaskResource::class,
            'route_name' => 'trello.rest.task',
            'route_identifier_name' => 'task_id',
            'collection_name' => 'task',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'POST',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
                2 => 'PATCH',
                3 => 'PUT',
                4 => 'DELETE',
            ],
            'collection_query_whitelist' => [],
            'page_size' => '25',
            'page_size_param' => '',
            'entity_class' => \trello\V2\Rest\Task\TaskEntity::class,
            'collection_class' => \trello\V2\Rest\Task\TaskCollection::class,
            'service_name' => 'task',
        ],
        'trello\\V3\\Rest\\Board\\Controller' => [
            'listener' => \trello\V3\Rest\Board\BoardResource::class,
            'route_name' => 'trello.rest.board',
            'route_identifier_name' => 'board_id',
            'collection_name' => 'board',
            'entity_http_methods' => [
                0 => 'GET',
            ],
            'collection_http_methods' => [
                0 => 'GET',
            ],
            'collection_query_whitelist' => [],
            'page_size' => '25',
            'page_size_param' => '',
            'entity_class' => \trello\V3\Rest\Board\BoardEntity::class,
            'collection_class' => \trello\V3\Rest\Board\BoardCollection::class,
            'service_name' => 'board',
        ],
        'trello\\V3\\Rest\\Column\\Controller' => [
            'listener' => \trello\V3\Rest\Column\ColumnResource::class,
            'route_name' => 'trello.rest.column',
            'route_identifier_name' => 'column_id',
            'collection_name' => 'column',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'DELETE',
                2 => 'PUT',
                3 => 'PATCH',
            ],
            'collection_http_methods' => [
                0 => 'POST',
                1 => 'PATCH',
                2 => 'PUT',
            ],
            'collection_query_whitelist' => [],
            'page_size' => '25',
            'page_size_param' => '',
            'entity_class' => \trello\V3\Rest\Column\ColumnEntity::class,
            'collection_class' => \trello\V3\Rest\Column\ColumnCollection::class,
            'service_name' => 'column',
        ],
        'trello\\V3\\Rest\\Task\\Controller' => [
            'listener' => \trello\V3\Rest\Task\TaskResource::class,
            'route_name' => 'trello.rest.task',
            'route_identifier_name' => 'task_id',
            'collection_name' => 'task',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'POST',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
                2 => 'PATCH',
                3 => 'PUT',
                4 => 'DELETE',
            ],
            'collection_query_whitelist' => [],
            'page_size' => '25',
            'page_size_param' => '',
            'entity_class' => \trello\V3\Rest\Task\TaskEntity::class,
            'collection_class' => \trello\V3\Rest\Task\TaskCollection::class,
            'service_name' => 'task',
        ],
    ],
    'api-tools-content-negotiation' => [
        'controllers' => [
            'trello\\V1\\Rest\\Board\\Controller' => 'HalJson',
            'trello\\V1\\Rest\\Column\\Controller' => 'HalJson',
            'trello\\V1\\Rest\\Task\\Controller' => 'HalJson',
            'trello\\V2\\Rest\\Board\\Controller' => 'HalJson',
            'trello\\V2\\Rest\\Column\\Controller' => 'HalJson',
            'trello\\V2\\Rest\\Task\\Controller' => 'HalJson',
            'trello\\V3\\Rest\\Board\\Controller' => 'HalJson',
            'trello\\V3\\Rest\\Column\\Controller' => 'HalJson',
            'trello\\V3\\Rest\\Task\\Controller' => 'HalJson',
        ],
        'accept_whitelist' => [
            'trello\\V1\\Rest\\Board\\Controller' => [
                0 => 'application/vnd.trello.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
                3 => 'application/vnd.trello.v1+json',
                4 => 'application/hal+json',
                5 => 'application/json',
            ],
            'trello\\V1\\Rest\\Column\\Controller' => [
                0 => 'application/vnd.trello.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
                3 => 'application/vnd.trello.v1+json',
                4 => 'application/hal+json',
                5 => 'application/json',
            ],
            'trello\\V1\\Rest\\Task\\Controller' => [
                0 => 'application/vnd.trello.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
                3 => 'application/vnd.trello.v1+json',
                4 => 'application/hal+json',
                5 => 'application/json',
            ],
            'trello\\V2\\Rest\\Board\\Controller' => [
                0 => 'application/vnd.trello.v2+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'trello\\V2\\Rest\\Column\\Controller' => [
                0 => 'application/vnd.trello.v2+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'trello\\V2\\Rest\\Task\\Controller' => [
                0 => 'application/vnd.trello.v2+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'trello\\V3\\Rest\\Board\\Controller' => [
                0 => 'application/vnd.trello.v3+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'trello\\V3\\Rest\\Column\\Controller' => [
                0 => 'application/vnd.trello.v3+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'trello\\V3\\Rest\\Task\\Controller' => [
                0 => 'application/vnd.trello.v3+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
        ],
        'content_type_whitelist' => [
            'trello\\V1\\Rest\\Board\\Controller' => [
                0 => 'application/vnd.trello.v1+json',
                1 => 'application/json',
                2 => 'application/vnd.trello.v1+json',
                3 => 'application/json',
            ],
            'trello\\V1\\Rest\\Column\\Controller' => [
                0 => 'application/vnd.trello.v1+json',
                1 => 'application/json',
                2 => 'application/vnd.trello.v1+json',
                3 => 'application/json',
            ],
            'trello\\V1\\Rest\\Task\\Controller' => [
                0 => 'application/vnd.trello.v1+json',
                1 => 'application/json',
                2 => 'application/vnd.trello.v1+json',
                3 => 'application/json',
            ],
            'trello\\V2\\Rest\\Board\\Controller' => [
                0 => 'application/vnd.trello.v2+json',
                1 => 'application/json',
            ],
            'trello\\V2\\Rest\\Column\\Controller' => [
                0 => 'application/vnd.trello.v2+json',
                1 => 'application/json',
            ],
            'trello\\V2\\Rest\\Task\\Controller' => [
                0 => 'application/vnd.trello.v2+json',
                1 => 'application/json',
            ],
            'trello\\V3\\Rest\\Board\\Controller' => [
                0 => 'application/vnd.trello.v3+json',
                1 => 'application/json',
            ],
            'trello\\V3\\Rest\\Column\\Controller' => [
                0 => 'application/vnd.trello.v3+json',
                1 => 'application/json',
            ],
            'trello\\V3\\Rest\\Task\\Controller' => [
                0 => 'application/vnd.trello.v3+json',
                1 => 'application/json',
            ],
        ],
    ],
    'api-tools-hal' => [
        'metadata_map' => [
            \trello\V1\Rest\Board\BoardEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'trello.rest.board',
                'route_identifier_name' => 'board_id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \trello\V1\Rest\Board\BoardCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'trello.rest.board',
                'route_identifier_name' => 'board_id',
                'is_collection' => '1',
            ],
            \trello\V1\Rest\Column\ColumnEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'trello.rest.column',
                'route_identifier_name' => 'column_id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \trello\V1\Rest\Column\ColumnCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'trello.rest.column',
                'route_identifier_name' => 'column_id',
                'is_collection' => '1',
            ],
            \trello\V1\Rest\Task\TaskEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'trello.rest.task',
                'route_identifier_name' => 'task_id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \trello\V1\Rest\Task\TaskCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'trello.rest.task',
                'route_identifier_name' => 'task_id',
                'is_collection' => '1',
            ],
            \trello\V2\Rest\Board\BoardEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'trello.rest.board',
                'route_identifier_name' => 'board_id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \trello\V2\Rest\Board\BoardCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'trello.rest.board',
                'route_identifier_name' => 'board_id',
                'is_collection' => '1',
            ],
            \trello\V2\Rest\Column\ColumnEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'trello.rest.column',
                'route_identifier_name' => 'column_id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \trello\V2\Rest\Column\ColumnCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'trello.rest.column',
                'route_identifier_name' => 'column_id',
                'is_collection' => '1',
            ],
            \trello\V2\Rest\Task\TaskEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'trello.rest.task',
                'route_identifier_name' => 'task_id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \trello\V2\Rest\Task\TaskCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'trello.rest.task',
                'route_identifier_name' => 'task_id',
                'is_collection' => '1',
            ],
            \trello\V3\Rest\Board\BoardEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'trello.rest.board',
                'route_identifier_name' => 'board_id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \trello\V3\Rest\Board\BoardCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'trello.rest.board',
                'route_identifier_name' => 'board_id',
                'is_collection' => '1',
            ],
            \trello\V3\Rest\Column\ColumnEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'trello.rest.column',
                'route_identifier_name' => 'column_id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \trello\V3\Rest\Column\ColumnCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'trello.rest.column',
                'route_identifier_name' => 'column_id',
                'is_collection' => '1',
            ],
            \trello\V3\Rest\Task\TaskEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'trello.rest.task',
                'route_identifier_name' => 'task_id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \trello\V3\Rest\Task\TaskCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'trello.rest.task',
                'route_identifier_name' => 'task_id',
                'is_collection' => '1',
            ],
        ],
    ],
    'api-tools-content-validation' => [
        'trello\\V1\\Rest\\Board\\Controller' => [
            'input_filter' => 'trello\\V1\\Rest\\Board\\Validator',
        ],
        'trello\\V2\\Rest\\Board\\Controller' => [
            'input_filter' => 'trello\\V2\\Rest\\Board\\Validator',
        ],
        'trello\\V3\\Rest\\Board\\Controller' => [
            'input_filter' => 'trello\\V3\\Rest\\Board\\Validator',
        ],
    ],
    'input_filter_specs' => [
        'trello\\V1\\Rest\\Board\\Validator' => [
            0 => [
                'required' => false,
                'validators' => [],
                'filters' => [],
                'name' => 'name',
            ],
            1 => [
                'required' => '',
                'validators' => [],
                'filters' => [],
                'name' => 'name',
            ],
        ],
        'trello\\V2\\Rest\\Board\\Validator' => [
            0 => [
                'required' => '',
                'validators' => [],
                'filters' => [],
                'name' => 'name',
            ],
        ],
        'trello\\V3\\Rest\\Board\\Validator' => [
            0 => [
                'required' => '',
                'validators' => [],
                'filters' => [],
                'name' => 'name',
            ],
        ],
    ],
    'api-tools-mvc-auth' => [
        'authorization' => [
            'trello\\V2\\Rest\\Board\\Controller' => [
                'collection' => [
                    'GET' => false,
                    'POST' => false,
                    'PUT' => false,
                    'PATCH' => false,
                    'DELETE' => false,
                ],
                'entity' => [
                    'GET' => false,
                    'POST' => false,
                    'PUT' => false,
                    'PATCH' => false,
                    'DELETE' => false,
                ],
            ],
            'trello\\V2\\Rest\\Column\\Controller' => [
                'collection' => [
                    'GET' => false,
                    'POST' => false,
                    'PUT' => false,
                    'PATCH' => false,
                    'DELETE' => false,
                ],
                'entity' => [
                    'GET' => false,
                    'POST' => false,
                    'PUT' => false,
                    'PATCH' => false,
                    'DELETE' => false,
                ],
            ],
            'trello\\V2\\Rest\\Task\\Controller' => [
                'collection' => [
                    'GET' => false,
                    'POST' => false,
                    'PUT' => false,
                    'PATCH' => false,
                    'DELETE' => false,
                ],
                'entity' => [
                    'GET' => false,
                    'POST' => false,
                    'PUT' => false,
                    'PATCH' => false,
                    'DELETE' => false,
                ],
            ],
            'trello\\V3\\Rest\\Board\\Controller' => [
                'collection' => [
                    'GET' => true,
                    'POST' => false,
                    'PUT' => false,
                    'PATCH' => false,
                    'DELETE' => false,
                ],
                'entity' => [
                    'GET' => true,
                    'POST' => false,
                    'PUT' => false,
                    'PATCH' => false,
                    'DELETE' => false,
                ],
            ],
            'trello\\V3\\Rest\\Column\\Controller' => [
                'collection' => [
                    'GET' => '',
                    'POST' => '',
                    'PUT' => '',
                    'PATCH' => '',
                    'DELETE' => '',
                ],
                'entity' => [
                    'GET' => '',
                    'POST' => '',
                    'PUT' => '',
                    'PATCH' => '',
                    'DELETE' => '',
                ],
            ],
            'trello\\V3\\Rest\\Task\\Controller' => [
                'collection' => [
                    'GET' => '',
                    'POST' => '',
                    'PUT' => '',
                    'PATCH' => '',
                    'DELETE' => '',
                ],
                'entity' => [
                    'GET' => '',
                    'POST' => '',
                    'PUT' => '',
                    'PATCH' => '',
                    'DELETE' => '',
                ],
            ],
        ],
    ],
];
